// src/routes/docs/[product=product]/[version]/[...slug]/+page.svelte
<script lang="ts">
  import {
    TableOfContents,
    Header,
    TabGroups,
    DocLayout,
    CategoryIndex,
    HotReloadIndicator,
    DevModeBadge,
    MdxHotReload,
    MdxContent,
    NotFoundContent,
    SearchHighlight,
    MobileDocLayout,
    mdxComponents,
  } from 'specra/components';
  import DocLoginGate from '$lib/components/DocLoginGate.svelte';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();

  // Type-compatible wrappers for component props
  let allDocsCompat: any[] = $derived(data.allDocs);
  let previousDoc = $derived(data.previous ?? undefined);
  let nextDoc = $derived(data.next ?? undefined);
  let categoryTitle = $derived(data.categoryTitle ?? undefined);
  let categoryDescription = $derived(data.categoryDescription ?? undefined);
</script>

<svelte:head>
  <title>{data.title}</title>
  <meta name="description" content={data.description} />
  <meta property="og:title" content={data.title} />
  <meta property="og:description" content={data.description} />
  <meta property="og:url" content={data.ogUrl} />
  <meta property="og:site_name" content="Documentation Platform" />
  <meta property="og:type" content="article" />
  <meta property="og:locale" content="en_US" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content={data.title} />
  <meta name="twitter:description" content={data.description} />
  <link rel="canonical" href={data.ogUrl} />
</svelte:head>

{#if !data.doc && data.isCategory}
  <!-- Category page without doc content -->
  <MobileDocLayout
    docs={allDocsCompat}
    version={data.version}
    product={data.product}
    config={data.config}
    activeTabGroup={data.categoryTabGroup}
  >
    {#snippet header()}
      <Header currentVersion={data.version} versions={data.versions} versionsMeta={data.versionsMeta} versionBanner={data.versionBanner} config={data.config} products={data.products} currentProduct={data.product}>
        {#snippet subheader()}
          {#if data.config.navigation?.tabGroups && data.config.navigation.tabGroups.length > 0}
            <TabGroups
              tabGroups={data.config.navigation.tabGroups}
              activeTabId={data.categoryTabGroup}
              docs={allDocsCompat}
              version={data.version}
              product={data.product}
              flush={data.config.navigation?.sidebarStyle === 'flush'}
            />
          {/if}
        {/snippet}
      </Header>
    {/snippet}
    <CategoryIndex
      categoryPath={data.slug}
      version={data.version}
      product={data.product}
      allDocs={allDocsCompat}
      title={categoryTitle}
      description={categoryDescription}
      config={data.config}
    />
  </MobileDocLayout>
  <MdxHotReload />
  <HotReloadIndicator />
  <DevModeBadge />
{:else if data.isProtected}
  <!-- Protected page — requires social login -->
  <MobileDocLayout
    docs={allDocsCompat}
    version={data.version}
    product={data.product}
    config={data.config}
  >
    {#snippet header()}
      <Header currentVersion={data.version} versions={data.versions} versionsMeta={data.versionsMeta} versionBanner={data.versionBanner} config={data.config} products={data.products} currentProduct={data.product}>
        {#snippet subheader()}
          {#if data.config.navigation?.tabGroups && data.config.navigation.tabGroups.length > 0}
            <TabGroups
              tabGroups={data.config.navigation.tabGroups}
              activeTabId={data.categoryTabGroup}
              docs={allDocsCompat}
              version={data.version}
              product={data.product}
              flush={data.config.navigation?.sidebarStyle === 'flush'}
            />
          {/if}
        {/snippet}
      </Header>
    {/snippet}
    <DocLoginGate slug={data.slug} version={data.version} />
  </MobileDocLayout>
  <MdxHotReload />
  <HotReloadIndicator />
  <DevModeBadge />
{:else if data.isNotFound}
  <!-- Not found -->
  <MobileDocLayout
    docs={allDocsCompat}
    version={data.version}
    product={data.product}
    config={data.config}
  >
    {#snippet header()}
      <Header currentVersion={data.version} versions={data.versions} versionsMeta={data.versionsMeta} versionBanner={data.versionBanner} config={data.config} products={data.products} currentProduct={data.product}>
        {#snippet subheader()}
          {#if data.config.navigation?.tabGroups && data.config.navigation.tabGroups.length > 0}
            <TabGroups
              tabGroups={data.config.navigation.tabGroups}
              activeTabId={data.categoryTabGroup}
              docs={allDocsCompat}
              version={data.version}
              product={data.product}
              flush={data.config.navigation?.sidebarStyle === 'flush'}
            />
          {/if}
        {/snippet}
      </Header>
    {/snippet}
    <NotFoundContent version={data.version} />
  </MobileDocLayout>
  <MdxHotReload />
  <HotReloadIndicator />
  <DevModeBadge />
{:else if data.doc}
  <!-- Normal doc or category with doc content -->
  <MobileDocLayout
    docs={allDocsCompat}
    version={data.version}
    product={data.product}
    config={data.config}
    activeTabGroup={data.categoryTabGroup}
  >
    {#snippet header()}
      <Header currentVersion={data.version} versions={data.versions} versionsMeta={data.versionsMeta} versionBanner={data.versionBanner} config={data.config} products={data.products} currentProduct={data.product}>
        {#snippet subheader()}
          {#if data.config.navigation?.tabGroups && data.config.navigation.tabGroups.length > 0}
            <TabGroups
              tabGroups={data.config.navigation.tabGroups}
              activeTabId={data.categoryTabGroup}
              docs={allDocsCompat}
              version={data.version}
              product={data.product}
              flush={data.config.navigation?.sidebarStyle === 'flush'}
            />
          {/if}
        {/snippet}
      </Header>
    {/snippet}
    {#snippet toc()}
      {#if !data.isCategory}
        <TableOfContents items={data.toc} config={data.config} />
      {/if}
    {/snippet}

    {#if data.isCategory}
      {#snippet categoryContent()}
        {#if data.doc?.contentNodes}
          <MdxContent nodes={data.doc.contentNodes} components={mdxComponents} />
        {:else if data.doc?.content}
          {@html data.doc.content}
        {/if}
      {/snippet}
      <CategoryIndex
        categoryPath={data.slug}
        version={data.version}
        allDocs={allDocsCompat}
        title={data.doc.meta.title}
        description={data.doc.meta.description}
        content={categoryContent}
        config={data.config}
      />
    {:else}
      <SearchHighlight />
      <DocLayout
        meta={data.doc.meta}
        previousDoc={previousDoc}
        nextDoc={nextDoc}
        version={data.version}
        slug={data.slug}
        product={data.product}
        config={data.config}
      >
        {#if data.doc.contentNodes}
          <MdxContent nodes={data.doc.contentNodes} components={mdxComponents} />
        {:else}
          {@html data.doc.content}
        {/if}
      </DocLayout>
    {/if}
  </MobileDocLayout>
  <MdxHotReload />
  <HotReloadIndicator />
  <DevModeBadge />
{/if}

// app/docs/[version]/[...slug]/page.tsx
import type { Metadata } from "next"
import { Suspense } from "react"
import {
  extractTableOfContents,
  getAdjacentDocs,
  isCategoryPage,
  getCachedVersions,
  getCachedAllDocs,
  getCachedDocBySlug,
  getI18nConfig,
  getConfig,
} from "specra/lib"
import {
  TableOfContents,
  Header,
  DocLayoutWrapper,
  HotReloadIndicator,
  DevModeBadge,
  MdxHotReload,
  NotFoundContent,
  DocLoading,
  SearchHighlight,
} from "specra/components"
import { CategoryIndex, DocLayout } from "specra/layouts"
import { mdxComponents } from "specra/mdx-components"
// import { mdxComponents } from "specra/mdx-components"

interface PageProps {
  params: Promise<{
    version: string
    slug: string[]
  }>
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { version, slug: slugArray } = await params
  const slug = slugArray.join("/")
  const doc = await getCachedDocBySlug(slug, version)

  if (!doc) {
    return {
      title: "Page Not Found",
      description: "The requested documentation page could not be found.",
    }
  }

  const title = doc.meta.title || doc.title
  const description = doc.meta.description || `Documentation for ${title}`
  const url = `/docs/${version}/${slug}`

  return {
    title: `${title}`,
    description,
    openGraph: {
      title,
      description,
      url,
      siteName: "Documentation Platform",
      type: "article",
      locale: "en_US",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
    alternates: {
      canonical: url,
    },
  }
}

export async function generateStaticParams() {
  const versions = getCachedVersions()
  const params = []

  for (const version of versions) {
    const docs = await getCachedAllDocs(version, 'all')
    for (const doc of docs) {
      params.push({
        version,
        slug: doc.slug.split("/").filter(Boolean),
      })
    }
  }

  return params
}

export default async function DocPage({ params }: PageProps) {
  const { version, slug: slugArray } = await params
  const slug = slugArray.join("/")

  const i18nConfig = getI18nConfig()
  let locale: string | undefined
  if (i18nConfig && i18nConfig.locales.includes(slugArray[0])) {
    locale = slugArray[0]
  }

  const allDocs = await getCachedAllDocs(version, locale)
  const versions = getCachedVersions()
  const config = getConfig()
  const isCategory = isCategoryPage(slug, allDocs)
  const doc = await getCachedDocBySlug(slug, version)

  if (!doc && isCategory) {
    const categoryDoc = allDocs.find((d) => d.slug.startsWith(slug + "/"))
    const categoryTabGroup = categoryDoc?.meta?.tab_group || categoryDoc?.categoryTabGroup

    return (
      <>
        <DocLayoutWrapper
          key={'doc-layout'}
          header={<Header currentVersion={version} versions={versions} config={config} />}
          docs={allDocs}
          version={version}
          toc={<div />}
          config={config}
          currentPageTabGroup={categoryTabGroup}
        >
          <CategoryIndex
            categoryPath={slug}
            version={version}
            allDocs={allDocs}
            title={slug.split("/").pop()?.replace(/-/g, " ").replace(/\b\w/g, (l) => l.toUpperCase()) || "Category"}
            description="Browse the documentation in this section."
            config={config}
            mdxComponents={mdxComponents}
          />
        </DocLayoutWrapper>
        <MdxHotReload />
        <HotReloadIndicator />
        <DevModeBadge />
      </>
    )
  }

  if (!doc) {
    return (
      <>
        <Suspense fallback={<DocLoading />}>
          <DocLayoutWrapper
            header={<Header currentVersion={version} versions={versions} config={config} />}
            docs={allDocs}
            version={version}
            toc={<div />}
            config={config}
            currentPageTabGroup={undefined}
          >
            <NotFoundContent version={version} />
          </DocLayoutWrapper>
          <MdxHotReload />
          <HotReloadIndicator />
          <DevModeBadge />
        </Suspense>
      </>
    )
  }

  const toc = extractTableOfContents(doc.content)
  const { previous, next } = getAdjacentDocs(slug, allDocs)
  const showCategoryIndex = isCategory && doc
  const currentPageTabGroup = doc.meta?.tab_group || doc.categoryTabGroup

  return (
    <>
      <Suspense fallback={<DocLoading />}>
        <DocLayoutWrapper
          header={<Header currentVersion={version} versions={versions} config={config} />}
          docs={allDocs}
          version={version}
          toc={showCategoryIndex ? <div /> : <TableOfContents key={'toc'} items={toc} config={config} />}
          config={config}
          currentPageTabGroup={currentPageTabGroup}
        >
          {showCategoryIndex ? (
            <CategoryIndex
              key="category-index"
              categoryPath={slug}
              version={version}
              allDocs={allDocs}
              title={doc.meta.title}
              description={doc.meta.description}
              content={doc.content}
              config={config}
              mdxComponents={mdxComponents}
            />
          ) : (
            <>
              <SearchHighlight />
              <DocLayout
                key="doc-layout"
                meta={doc.meta}
                content={doc.content}
                previousDoc={previous ? { title: previous.meta.title, slug: previous.slug } : undefined}
                nextDoc={next ? { title: next.meta.title, slug: next.slug } : undefined}
                version={version}
                slug={slug}
                config={config}
                mdxComponents={mdxComponents}
              />
            </>
          )}
        </DocLayoutWrapper>
        <MdxHotReload />
        <HotReloadIndicator />
        <DevModeBadge />
      </Suspense>
    </>
  )
}
