// src/routes/dashboard/projects/new/+page.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { Building2 } from 'lucide-svelte';

  const orgId = $derived($page.url.searchParams.get('orgId'));

  let name = $state('');
  let slug = $state('');
  let error = $state('');
  let loading = $state(false);
  let orgName = $state<string | null>(null);
  let orgLoading = $state(!!$page.url.searchParams.get('orgId'));

  $effect(() => {
    if (!orgId) return;
    fetch(`/api/organizations/${orgId}`)
      .then((res) => {
        if (!res.ok) throw new Error();
        return res.json();
      })
      .then((org) => {
        orgName = org.name;
      })
      .catch(() => {
        orgName = null;
      })
      .finally(() => {
        orgLoading = false;
      });
  });

  function handleNameChange(value: string) {
    name = value;
    slug = value
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-');
  }

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    error = '';
    loading = true;

    try {
      const res = await fetch('/api/projects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, slug, ...(orgId ? { orgId } : {}) }),
      });

      if (!res.ok) {
        const data = await res.json();
        error = data.error || 'Failed to create project';
        return;
      }

      const project = await res.json();
      goto(`/dashboard/projects/${project.id}`);
    } catch {
      error = 'Something went wrong';
    } finally {
      loading = false;
    }
  }
</script>

<div class="max-w-lg space-y-6">
  <div>
    <h1 class="text-2xl font-bold text-foreground">New Project</h1>
    <p class="text-muted-foreground mt-1">
      Create a new docs project to deploy online.
    </p>
  </div>

  {#if orgLoading}
    <div class="rounded-md border border-border bg-accent/50 px-4 py-3 text-sm text-muted-foreground">
      Loading organization...
    </div>
  {:else if orgId && orgName}
    <div class="flex items-center gap-2 rounded-md border border-border bg-accent/50 px-4 py-3 text-sm">
      <Building2 class="h-4 w-4 text-muted-foreground" />
      <span class="text-muted-foreground">
        Creating project in
        <span class="font-medium text-foreground">{orgName}</span>
      </span>
    </div>
  {:else}
    <div class="rounded-md border border-border bg-accent/50 px-4 py-3 text-sm text-muted-foreground">
      Creating personal project
    </div>
  {/if}

  <form onsubmit={handleSubmit} class="space-y-4">
    <div>
      <label
        for="name"
        class="block text-sm font-medium text-foreground mb-1"
      >
        Project Name
      </label>
      <input
        id="name"
        type="text"
        value={name}
        oninput={(e) => handleNameChange((e.target as HTMLInputElement).value)}
        placeholder="My Docs"
        required
        class="w-full rounded-md border border-border bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-foreground/20"
      />
    </div>

    <div>
      <label
        for="slug"
        class="block text-sm font-medium text-foreground mb-1"
      >
        Subdomain
      </label>
      <div class="flex items-center gap-0">
        <input
          id="slug"
          type="text"
          bind:value={slug}
          oninput={(e) => {
            slug = (e.target as HTMLInputElement).value.toLowerCase().replace(/[^a-z0-9-]/g, '');
          }}
          placeholder="my-docs"
          required
          pattern="^[a-z0-9-]+$"
          class="w-full rounded-l-md border border-border bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-foreground/20"
        />
        <span class="rounded-r-md border border-l-0 border-border bg-accent px-3 py-2 text-sm text-muted-foreground whitespace-nowrap">
          .docs.specra.dev
        </span>
      </div>
    </div>

    {#if error}
      <p class="text-sm text-destructive">{error}</p>
    {/if}

    <button
      type="submit"
      disabled={loading || !name || !slug}
      class="w-full rounded-md bg-foreground px-4 py-2 text-sm font-medium text-background hover:bg-foreground/90 disabled:opacity-50 transition-colors"
    >
      {loading ? 'Creating...' : 'Create Project'}
    </button>
  </form>
</div>

// app/dashboard/projects/new/page.tsx
"use client"

import { useState, useEffect, Suspense } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import { Building2 } from "lucide-react"

function NewProjectForm() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const orgId = searchParams.get("orgId")

  const [name, setName] = useState("")
  const [slug, setSlug] = useState("")
  const [error, setError] = useState("")
  const [loading, setLoading] = useState(false)
  const [orgName, setOrgName] = useState<string | null>(null)
  const [orgLoading, setOrgLoading] = useState(!!orgId)

  useEffect(() => {
    if (!orgId) return
    fetch(`/api/organizations/${orgId}`)
      .then((res) => {
        if (!res.ok) throw new Error()
        return res.json()
      })
      .then((org) => setOrgName(org.name))
      .catch(() => setOrgName(null))
      .finally(() => setOrgLoading(false))
  }, [orgId])

  function handleNameChange(value: string) {
    setName(value)
    setSlug(
      value
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, "")
        .replace(/\s+/g, "-")
    )
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setError("")
    setLoading(true)

    try {
      const res = await fetch("/api/projects", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, slug, ...(orgId ? { orgId } : {}) }),
      })

      if (!res.ok) {
        const data = await res.json()
        setError(data.error || "Failed to create project")
        return
      }

      const project = await res.json()
      router.push(`/dashboard/projects/${project.id}`)
    } catch {
      setError("Something went wrong")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-lg space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">New Project</h1>
        <p className="text-muted-foreground mt-1">
          Create a new docs project to deploy online.
        </p>
      </div>

      {orgLoading ? (
        <div className="rounded-md border border-border bg-accent/50 px-4 py-3 text-sm text-muted-foreground">
          Loading organization...
        </div>
      ) : orgId && orgName ? (
        <div className="flex items-center gap-2 rounded-md border border-border bg-accent/50 px-4 py-3 text-sm">
          <Building2 className="h-4 w-4 text-muted-foreground" />
          <span className="text-muted-foreground">
            Creating project in{" "}
            <span className="font-medium text-foreground">{orgName}</span>
          </span>
        </div>
      ) : (
        <div className="rounded-md border border-border bg-accent/50 px-4 py-3 text-sm text-muted-foreground">
          Creating personal project
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label
            htmlFor="name"
            className="block text-sm font-medium text-foreground mb-1"
          >
            Project Name
          </label>
          <input
            id="name"
            type="text"
            value={name}
            onChange={(e) => handleNameChange(e.target.value)}
            placeholder="My Docs"
            required
            className="w-full rounded-md border border-border bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-foreground/20"
          />
        </div>

        <div>
          <label
            htmlFor="slug"
            className="block text-sm font-medium text-foreground mb-1"
          >
            Subdomain
          </label>
          <div className="flex items-center gap-0">
            <input
              id="slug"
              type="text"
              value={slug}
              onChange={(e) => setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ""))}
              placeholder="my-docs"
              required
              pattern="^[a-z0-9-]+$"
              className="w-full rounded-l-md border border-border bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-foreground/20"
            />
            <span className="rounded-r-md border border-l-0 border-border bg-accent px-3 py-2 text-sm text-muted-foreground whitespace-nowrap">
              .docs.specra.dev
            </span>
          </div>
        </div>

        {error && (
          <p className="text-sm text-destructive">{error}</p>
        )}

        <button
          type="submit"
          disabled={loading || !name || !slug}
          className="w-full rounded-md bg-foreground px-4 py-2 text-sm font-medium text-background hover:bg-foreground/90 disabled:opacity-50 transition-colors"
        >
          {loading ? "Creating..." : "Create Project"}
        </button>
      </form>
    </div>
  )
}

export default function NewProjectPage() {
  return (
    <Suspense
      fallback={
        <div className="max-w-lg space-y-6">
          <div>
            <h1 className="text-2xl font-bold text-foreground">New Project</h1>
            <p className="text-muted-foreground mt-1">Loading...</p>
          </div>
        </div>
      }
    >
      <NewProjectForm />
    </Suspense>
  )
}
